### ISSUE TITLE
Example of actually using it inside the same cluster

### ISSUE THREAD

**Issue by AntonOfTheWoods** [oscar6echo/fief-k3d-deploy#1]
While awesome, this suffers from exactly the same issue as the upstream docker compose example - it doesn't give any example of actually *using* the instance *from inside the cluster*. There seem to be persistent issues with the actual host name that is declared and that which can be used. You need to use localhost to get various things without https (like copying the `client_id` and `client_secret`) but you obviously can't use localhost in docker or kube for actually referencing anything. From discussions there *appears* to be a config option on the `FiefAsync` class (for Python) but without an example simply setting this just doesn't work.

**Comment by oscar6echo** [comment]
This repo attempts to do the same as the docker compose based official doc [self hosting](https://docs.fief.dev/self-hosting/deployment/docker-compose/) section, only for kube. Why ? Because kube is often used for deployment.  

But it does not go further: It does not provide an app using this fief deployment.

 You ask several kube generic questions, unrelated to fief:
+ While https is necessary in a real world deployment, it adds complexity in a local deploy, irrespective of the app, e.g. fief. If you want have https locally, I'd recommend [mkcert](https://github.com/FiloSottile/mkcert) certificates. To use TLS at ingress level see [official doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls).
+ Intra kube cluster pod to pod com: Check out `REDIS_URL` in [kustomize/ephemeral/configmap-fief.yml](https://github.com/oscar6echo/fief-k3d-deploy/blob/main/kustomize/ephemeral/configmap-fief.yml) as an example. Generic url = `protocol://[service-name].svc.cluster.local:[service-port]`. But a pod can also a public url ie one exposed by the ingress - AND the load balancer in the very specific case of local k3d.

In general to (maybe) reassure you: It is _EXPECTED_ to get confused with the several nested "localhosts" involved in a local k3d deployement: your machine, the kube ingress, the docker internal.host, your machine firewall !  
I tried to add more info in the [README](https://github.com/oscar6echo/fief-k3d-deploy/blob/main/README.md).

k3d nesting is hard at first, but once understood, it is quite close to a real deployment, so most of it can be reused as-is.

Now about your main point: Yes it would be good for fief to provide a full fledged deployment recipe with a demo app using it.

**Comment by AntonOfTheWoods** [comment]
Actually one of the key problems is that - at least I couldn't work out how (maybe via the API?) - it is simply not possible to use fief in this configuration. Why? Because to get the generated client secret for a client you need to click on the "copy" button, but that is not possible when you are not using a secure URL (localhost or https). So that is very related to fief. I *believe* it would be possible to use fief locally without using ssl for internal kube communication without this, though there may be other gotchas. Having an example made by someone who actually knows would make all of this clear!

**Comment by oscar6echo** [comment]
1/
I cannot reproduce - if I understand you well:

After a deploy I can copy client id and client secret using the button to this effect - no pb.  
The url is not https: `http://localhost:8080/admin`.  
Maybe a browser config issue ?

![image](https://github.com/oscar6echo/fief-k3d-deploy/assets/2219383/1e8c0a34-5c11-497b-a058-0fc35a36caa7)

2/
I can also access the client info using an API key created on the admin page:

![image](https://github.com/oscar6echo/fief-k3d-deploy/assets/2219383/24e2abda-f1d9-44d3-ba0e-351d4bd7bf52)

Then auth on the swagger page using this api key:

![image](https://github.com/oscar6echo/fief-k3d-deploy/assets/2219383/551536dc-2f29-4896-a5ab-7aa792cee969)

3/
Finally it is always possible search for info in the database - you have full access - it is always telling to see how the data is stored:

![image](https://github.com/oscar6echo/fief-k3d-deploy/assets/2219383/1be9237c-41cb-4a6d-b07b-6a38d09052fb)


4/
Except for the db access, the admin dashboard and api swagger are accessible irrespective of whether the fief server is under your control.  

From there an app using fief does not care where it is hosted and does not have to be served in the same cluster/ns.  Frankly I think the "internal kube com" is misguided.

Maybe try and setup a basic app using their [cloud offer](https://www.fief.dev/) and when this works try substitute it with a local fief server (docker compose or kube).

**Comment by AntonOfTheWoods** [comment]
The problem is not with `localhost`, but with anything else. In docker you typically use the container name (or whatever it's called, service in kube), something like `fief`. If you then put that in your hosts and try and access it in a browser, certain things won't work, like the copy. You can't use localhost because you can't use localhost in your internal app (which is in another container in the same compose network) because docker will think it's your apps container rather than fief, and fief uses the hostname to recognise tenants (or is it clients, same diff anyway).

But anyway, it turns out that the project philosophy and features of fief is quite incompatible with my typical project requirements, so I'll let you guys discover that, and I've moved on! Frankly it was a colossal waste of time, apart from discovering the basics of kustomize. Thanks for that!

**Comment by oscar6echo** [comment]
> The problem is not with localhost, but with anything else. In docker you typically use the container name (or whatever it's called, service in kube), something like fief. If you then put that in your hosts and try and access it in a browser, certain things won't work, like the copy. You can't use localhost because you can't use localhost in your internal app (which is in another container in the same compose network) because docker will think it's your apps container rather than fief, and fief uses the hostname to recognise tenants (or is it clients, same diff anyway).

I could not provide more info without a working example to try and fix/improve.

> But anyway, it turns out that the project philosophy and features of fief is quite incompatible with my typical project requirements, so I'll let you guys discover that, and I've moved on! Frankly it was a colossal waste of time, apart from discovering the basics of kustomize. Thanks for that!

Fine. Indeed wrapping your head around fief and auth in general is not easy. Good luck.
